### ISSUE TITLE
Probleme ACL Redhat

### ISSUE THREAD

**Issue by Nidhal09** [linkdd/fwallsh#4]
Quand je tape ce code pour données acces  a un user dans un groupe 
sudo setfacl -m d:USER:rx DOSSIER 
je recois l'un de deux probleme le premier :

setfacl : Option -m : Argument invalide près du caractère 5

le deuxieme

liste d'argument trop longue 

merci pour votre reponse

**Comment by linkdd** [comment]
Cela n'a pas grand chose à voir avec ce dépôt qui n'est plus maintenu mais bon...

D'après https://linux.die.net/man/1/setfacl :

```
setfacl -m d:u:UID:rx DOSSIER
```

Il manquerait donc le `u:`.

**Comment by Nidhal09** [comment]
merci pour votre retour , j'ai ajouté u: et c'est bon , 
rien que **liste d'argument trop longue** s'affiche toujours
